# Generated by Django 5.2 on 2025-05-23 18:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='size',
            field=models.FloatField(help_text='Area in acres'),
        ),
    ]
