# Generated by Django 5.2 on 2025-05-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.AddField(
            model_name='device',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farm'),
            preserve_default=False,
        ),
    ]
