# Generated by Django 5.2 on 2025-05-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_farm_owner'),
        ('sensors', '0002_remove_device_location_device_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.farm'),
        ),
    ]
